### ISSUE TITLE
What is this? 

### ISSUE THREAD

**Issue by philips** [kubernetes/kube2consul#1]
What is this and where did it come from? Is there a documented set of processes about projects getting added to the organization?

**Comment by girishkalele** [comment]
The commit history shows @bgrant0607

**Comment by bgrant0607** [comment]
@philips New home for https://github.com/kubernetes/kubernetes/pull/26310

We can't add new things to the main repo. They have to be forked into other repos.

**Comment by philips** [comment]
@bgrant0607 I filed an issue about making the process for adding new repos more clear and setting a bar for inclusion. Would love to discuss: https://groups.google.com/forum/#!topic/kubernetes-dev/o6E1u-orDK8
